### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by karlkar** [stianaske/pybotvac#11]
Hi. 
I'm trying to use your awesome library with home-assistant. To do it I need your repository to have some releases. Could you please create some tags (at least for version 0.0.4)?

**Comment by qelanhari** [comment]
I'm interrested to know how you integrate with home assistant

**Comment by karlkar** [comment]
Home-assistant is currently using pybotvac from fork of this repository made by jabesq. If we could download the code from this repository using versioned URL, that would be great. All jabesq did in his version is adding a tags.

If you want to know how to configure Neato Robots in Home-assistant just serach the Home assistant docs for "neato".

**Comment by qelanhari** [comment]
Wow thanks ! Last time I checked (ok, maybe a long time ago) there was nothing :)

**Comment by stianaske** [comment]
Hi. I currently do not have access to a computer, but I will look into this
when I have the chance.

I actually recently started using homeassistant myself, so this is in my
interest as well. Awesome piece of software!

**Comment by stianaske** [comment]
Added release for v0.0.4. Let me know if any further changes are needed to better support Home Assistant.

**Comment by andrey-git** [comment]
@stianaske We are moving to pypi-only dependencies in Home Assistant. Could you create a pypi package for pybotvac?
