### ISSUE TITLE
404 Client Error with my robot

### ISSUE THREAD

**Issue by WeiYang1982** [stianaske/pybotvac#17]
I try to use pybotvac. when I get from https://beehive.neatocloud.com/users/me/robots/ the response will see my robot like this:
```
[{
        "serial": "GPC11418-7C3****E3F3",
        "prefix": "SN",
        "name": "my_robot",
        "model": "BotVacD5Connected",
        "timezone": null,
        "secret_key": "E42B******379C0",
        "purchased_at": "2018-06-16T00:00:00Z",
        "linked_at": "2018-07-11T13:32:08Z",
        "nucleo_url": "https://ap-nucleo.neatocloud.com:4443",
        "traits": [
            "maps"
        ],
        "proof_of_purchase_url": null,
        "proof_of_purchase_url_valid_for_seconds": 900,
        "proof_of_purchase_generated_at": null,
        "mac_address": "*********",
        "created_at": "2018-06-23T23:20:56Z"
    }]
```
but when I post for https://nucleo.neatocloud.com/vendors/neato/robots/GPC11418-7C3****E3F3/messages, I will get the error with "requests.exceptions.HTTPError: 404 Client Error: Not Found for url https://nucleo.neatocloud.com/vendors/neato/robots/GPC11418-7C3****E3F3/messages"

**Comment by stianaske** [comment]
I see you're coming from home-assistant. Do you get the same issue when using pybotvac directly? Do the following work?
```
from pybotvac import Account

a = Account(<user name>, <password>)
print(list(a.robots))
```

I see that your response lists `"nucleo_url": "https://ap-nucleo.neatocloud.com:4443"`.
When listing the robots from my own account I get a `"nucleo_url": "https://nucleo.neatocloud.com:4443"` which is the url that the later requests use. I would guess that the later robots use a different endpoint (I only have a Botvac Connected and am unable to check for D5/D7). 

Could you check if changing the endpoint to `"https://ap-nucleo.neatocloud.com:4443"` resolves your issue?

I can build a release where the robot endpoint is dynamic based on the robot response, as opposed to hardcoded as it is now.

**Comment by dshokouhi** [comment]
@stianaske I have a D7 and I do not have this issue so my endpoint must be the same as yours.

**Comment by stianaske** [comment]
@angelyangw I created a dev branch with a possible fix for this. Could you please download the [dev branch](https://github.com/stianaske/pybotvac/archive/dev.zip) and see if this resolves your issue?

**Comment by WeiYang1982** [comment]
@stianaske @dshokouhi Thank you for regard！ I use the dev branch and I try to change the endpoint to "https://ap-nucleo.neatocloud.com:4443"  It's work!!  Thank you guys!
Maybe the different country use the different endpoint?

**Comment by stianaske** [comment]
@angelyangw Great! I will merge this into the master branch and create a new release then.

**Comment by WeiYang1982** [comment]
Thanks a lot!

**Comment by avanshee** [comment]
Hi @stianaske. I am very new to this topic, I have a D5 botvac connected and was trying with the POST for https://nucleo.neatocloud.com:4443/vendors/neato/robots/OPS11117-04A****EE7F/messages using a debugger, given all possible headers and body, but I am also getting an error 

`{"message":"Could not find robot_serial for specified vendor_name"}`

My robot is online as I can control it from the app, the beehive API response is fine and getting me result as:

{

        "serial": "OPS11117-04A*****EE7F",
        "prefix": "SN",
        "name": "tuffy",
        "model": "BotVacD5Connected",
        "timezone": null,
        "secret_key": "1844B7DD63F5************60117EB5",
        "purchased_at": null,
        "linked_at": "2018-07-30T09:56:02Z",
        "nucleo_url": "https://nucleo.neatocloud.com:4443",
        "traits": []
    }

Could you please tell me what is possibly going wrong, and help me fixing it?
