### ISSUE TITLE
Error 403 (Permission denied) while trying to retrieve my serial and secret

### ISSUE THREAD

**Issue by Scorpion008** [stianaske/pybotvac#2]
Hello,

when I try to retrieve the serialnumber and secret of my robot, I only get the following error message. I tried to do it manually and used the sample.py-script, both without success.

> Traceback (most recent call last):
>   File "sample.py", line 6, in <module>
>     account = Account(email, password)
>   File "/usr/lib/python3.5/site-packages/pybotvac-0.0.1-py3.5.egg/pybotvac/account.py", line 21, in **init**
>     self._login(email, password)
>   File "/usr/lib/python3.5/site-packages/pybotvac-0.0.1-py3.5.egg/pybotvac/account.py", line 37, in _login
>     response.raise_for_status()
>   File "/usr/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://beehive.neatocloud.com/sessions

It looks like Neato tries to prevent this way of acessing their data. Is it still possible to use this script?

Thanks
Scorpion008

**Comment by Scorpion008** [comment]
Ok, I made a pretty stupid mistake and used the wrong password.

Thank you for your work.
Scorpion008

**Comment by stephan1827** [comment]
Hi,
I am trying to the sample to work but when I use my credentials I receive the following error message. I am familiar with software development but I am a total noob with python so there is pretty good chance I am just missing something. User name and password should be correct and work with Javascript used in ioBroker.

`Traceback (most recent call last):
  File "/Users/stephan/Documents/Development/Phyton/Neato/pybotvac-master/sample/sample.py", line 11, in <module>
    account = Account(email, password)
  File "/Library/Python/2.7/site-packages/pybotvac-0.0.13-py2.7.egg/pybotvac/account.py", line 33, in __init__
    self._login(email, password)
  File "/Library/Python/2.7/site-packages/pybotvac-0.0.13-py2.7.egg/pybotvac/account.py", line 51, in _login
    response.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://beehive.neatocloud.com/sessions`
