### ISSUE TITLE
Add Vorwerk Kobold?

### ISSUE THREAD

**Issue by krono** [stianaske/pybotvac#21]
Vorwerk (who brought Neato Robotics in 2017) makes a VR 200 robot that seems similar to the botvac.

Indeed, the openHAB neato bindings cope for that with a distinct ["vendor"](https://github.com/scurb/NeatoBinding/tree/master/src/main/java/org/openhab/binding/neato/internal).

Essentialy, two urls are different. The [endpoint/beehive](https://github.com/stianaske/pybotvac/blob/1b475da1f8debad4433f2b8e48a388fb62ccbfb7/pybotvac/account.py#L26) and the [nucleo](https://github.com/stianaske/pybotvac/blob/1b475da1f8debad4433f2b8e48a388fb62ccbfb7/pybotvac/robot.py#L22).
(see https://github.com/scurb/NeatoBinding/blob/master/src/main/java/org/openhab/binding/neato/internal/VendorVorwerk.java). Maybe these can be added?

**Comment by cobirnm** [comment]
I would also love that!!!

**Comment by darookee** [comment]
Looking at the OpenHAB implementation it looks like there needs to be done something more than just replacing the endpoint URIs. I also found a [nodejs implementation](https://github.com/nicoh88/node-kobold/blob/master/lib/client.js) which does exactly that. I wonder if something does not work without the SSL configuration or if it is just to silence the certificate verification.
