### ISSUE TITLE
Not able to fetch maps

### ISSUE THREAD

**Issue by quack3d** [stianaske/pybotvac#22]
I'm trying the example:

from pybotvac import Account
for map_info in Account('sample@email.com', 'sample_password').maps:
 print(map_info)

But I get no output in terminal. If I do the same for .robots it shows serial, key, name and Traits: ['maps'] like it should. I have 20 maps available in the Neato app.

**Comment by DeastinY** [comment]
same here

**Comment by dshokouhi** [comment]
hmm what botvac do you guys have?  I have a D7 and the map and map info is being pulled properly

**Comment by quack3d** [comment]
Botvac Connected.

**Comment by DeastinY** [comment]
D3 here

**Comment by stianaske** [comment]
Thanks for the input. This was a bug where we accidentally iterated over the internal list of robots instead of using the property which also refreshes the robot list. This caused the `maps` dict to be empty unless a robot had been accessed first. Resolved in version 0.0.10.
