### ISSUE TITLE
URL-lib 

### ISSUE THREAD

**Issue by larsvinc** [stianaske/pybotvac#27]
Imported pybotvac version 0.11 into my home assistant on docker by making a custom component and increasing the dependency on the version. It seems that removing the urlib did not work gracefully.

Parts of log output:
  File "/config/custom_components/neato.py", line 179, in __init__
    self._hass.data[NEATO_MAP_DATA] = self.my_neato.maps
  File "/config/deps/lib/python3.6/site-packages/pybotvac/account.py", line 74, in maps
    self.refresh_maps()
  File "/config/deps/lib/python3.6/site-packages/pybotvac/account.py", line 86, in refresh_maps
    requests.get(urllib.parse.urljoin(self.ENDPOINT,
NameError: name 'urllib' is not defined

I have confirmed that the library i pulled in is 0.11. I have also confirmed that it is working again by reverting to a import urllib as in the previous release.

**Comment by dshokouhi** [comment]
I see it too, if we add `import urllib` to line 9 inside the `try` block it works fine in account.py

**Comment by stianaske** [comment]
This should be resolved in the latest commit. I don't have the chance to test the changes now, but will test and push to pypi when I get home.

**Comment by dshokouhi** [comment]
just wanted to confirm that version 0.0.12 fixes this issue as well :)

@larsvinc if you plan to update home assistant with the spot cleaning service call I will hold off on submitting an update just let me know :) there is a current bug to get the D7 working so some are waiting for that.
