### ISSUE TITLE
Start cleaning doesn't work with Botvac D3 Connected after cleaning was stopped

### ISSUE THREAD

**Issue by Santobert** [stianaske/pybotvac#50]
Start Cleaning didn't do anything, when the robot is in standby mode after cleaning was stopped.

Reproduce:
1. Robot is docked
2. Start cleaning -> Robot starts cleaning
3. Stop cleaning -> Robot is in standby mode
4. Start cleaning -> Nothing happens

Can someone please verify this?

**Comment by Santobert** [comment]
Maybe thats related to #41 as the floorplan isn't available when the robot is not docked

**Comment by dshokouhi** [comment]
can you check the alert/error state after step 4? see if anything is returned in that call.  We were able to fix this for the D7 here: https://github.com/stianaske/pybotvac/blob/master/pybotvac/robot.py#L123 but I think D3 might be returning a different value or elsewhere in the state
