### ISSUE TITLE
Use oauth?

### ISSUE THREAD

**Issue by ostinelli** [stianaske/pybotvac#6]
Hello @stianaske!
Let me introduce myself, I am Roberto Ostinelli, Neato Robotics' Director of Cloud Services.

I'm impressed with the work that you've put into integrating with our robots! Great job!

Given the interest that we've seen from developers like yourself and around the forums we've listened and have just released the [Neato Developer Network](https://developers.neatorobotics.com). In there, amongst other things you will find official documentation and SDKs for JavaScript, iOS and Android (for now, we plan on expanding to other languages too!).

This issue is for you to consider switching to proper OAuth instead of the internal logins mechanisms that you are using in this gem.

It would be the official way to proceed, and you would avoid some improper implementations. For example, you should not pass `token` and `platform` [here](https://github.com/stianaske/pybotvac/blob/f75bb548c185795296b098fed47743f322f50a33/pybotvac/account.py#L37): they are not needed, raise errors on our systems - since tokens are invalid - and this could eventually result in the blocking of user accounts by our automated systems if abused. We definitely wouldn't want that!

Please note that all of this is in Beta, we're a small team but are doing our best!

All the best,
r.

PS: I've opened the same issue on the [gem](https://github.com/kangguru/botvac) that, to my knowledge, started it all. :)

**Comment by stianaske** [comment]
Hi @ostinelli,

That's great news. Thank you for listening to the community and releasing your documentation and SDKs!
I will of course make an effort to switch to proper OAuth as soon as possible.

**Comment by ostinelli** [comment]
Great to know! Let me know if we can help.

**Comment by da2x** [comment]
@ostinelli, is it okay for apps to not use OAuth2? OAuth2 is kind of [inconvenient to developers of desktop apps](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-03). Loopback or URI redirection means the secret will be included in the app and ultimately exposed to anyone who care to extract it from the binary. For open source programs, it’s pointless to even try to hide the OAuth2 secret. For desktop apps, setting up a URI redirect or loopback redirect also means the app needs higher privileges. It can’t be done in, say, a GNOME extension, KDE plasmoid, or macOS widget.

Sorry for hijacking the conversation, but this is probably relevant to most users of pybotvac.

**Comment by ostinelli** [comment]
@da2x secret isn't to be used with the `Grant Type: Implicit`, which is what is recommended for desktop or mobile apps. See [here](https://developers.neatorobotics.com/guides/oauth-flow) for more info (you'll need to login to the developer network).

If you don't use OAuth2 basically you're asking the users to give the applications their credentials. Furthermore our efforts will be concentrated into exposing public API with OAuth, so if you end up using non OAuth2 might be confronted with changing API and no official documentation.

**Comment by quack3d** [comment]
Any progress on implementing OAuth2 @stianaske ?

**Comment by fermulator** [comment]
Given the age of the issue- would Neato be willing to contribute and provide reference/example implementation, or even make it happen and submit a PR? (@ostinelli)

**Comment by fermulator** [comment]
Official documentation btw: https://developers.neatorobotics.com/api
