### ISSUE TITLE
BotVac D5 Does Not Work

### ISSUE THREAD

**Issue by kvermilion** [stianaske/pybotvac#8]
It appears that it assumed that each service is expected to be a particular version, which causes BotVac D5 not to work.

Would you mind if I work on a pull request to at least support other service versions (according to Neato's documentation), and possibly add other stuff that is now documented, but not exposed by pybotvac?

**Comment by karlkar** [comment]
Hi kvermilion.
I'm not the owner of the code, so this is not the response that you're waiting for, however I have Botvac D3 and it also doesn't work and I'm eager to add support for it. So maybe we could join our forces and at least compare what commands should be sent to each robot model?
Regards.

**Comment by kvermilion** [comment]
Hi karlkar,

Please try my branch: https://github.com/kvermilion/pybotvac

There are 3 different versions of the houseCleaning service in the Neato API docs--this should support all of them correctly.

Thanks.

**Comment by karlkar** [comment]
I'll try it later.  Where did you find the API docs?

**Comment by karlkar** [comment]
You can also check my commit, I've made it so it works with my D3 and should also work for other robots. It's in the pull requests already.

**Comment by kvermilion** [comment]
The API can be found here: https://developers.neatorobotics.com/api
There is an agreement, and then you can access it using your Neato login.

I took a look at your commit and I'm not convinced that it won't break support for the basic-1 version of the service. It'll be sending a superfluous navigationMode param, and I haven't seen anything in the docs that suggest that such a thing will be ignored.

**Comment by karlkar** [comment]
Ok. You're code looks more compatible with the API. I've reviewed it and left some notes. 
Create a pull request, maybe author will cone and accept it.

**Comment by stianaske** [comment]
Thanks for the input and the pull request. I did a few changes before merging into master:
- Create UnsupportedDevice exception class, to simplify catching exception in user code.
- Create read-only properties for available_services and service_version.
- Check that service version is supported once (in __init__), to avoid code duplication.
- Renamed a few variables for PEP 8 compliance.

Please verify that this works properly with D3 and D5.

**Comment by kvermilion** [comment]
All great changes.
It works on my D5.

Thanks.

**Comment by stianaske** [comment]
Great! Thanks alot for the contribution! Closing ticket.
